### ISSUE TITLE
Add new workshop Request https://learn-to-code.workshop.aws

### ISSUE THREAD

**Issue by charles545587** [dgomesbr/awesome-aws-workshops#11]
Can you add:

https://learn-to-code.workshop.aws

This is a new workshop which teaches the basics of python using  AWS tools and services.  It was written to address an identified gap that other blogs, tutorials and workshops required some prior knowledge of python, making it difficult for beginners to build on AWS.  It makes use of the Cloud9 IDE and Amazon Translate for examples. There are links to other workshops and new content will be added in the future.

**Comment by dgomesbr** [comment]
Closed by fbde155; Thank you Charles, you've been added to Contributors list.
