### ISSUE TITLE
Website link doesn't work in Containers section

### ISSUE THREAD

**Issue by StanForever** [dgomesbr/awesome-aws-workshops#34]
Can we please remove the website 'Amazon SageMaker + EKS + Kubeflow Workshop: Hands-On Distributed Training with TensorFlow, Keras, PyTorch, and MXNet' listed in 'Containers' section?

The [link](https://master.d2j834wqg8s4j0.amplifyapp.com/) to the website doesn't work.

**Comment by jfmcdowell** [comment]
For what it's worth I think that content has moved on to [Data Science on Amazon Web Services ](https://www.datascienceonaws.com), specifically this [repo](https://github.com/data-science-on-aws/workshop). I'm not sure if linking directly to the repo is appropriate for this site.
